server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: nghiadev
    password: nghia

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs

jwt:
  secret: Wzm99ojqlOKdLVXO+TzxUmhgcD8Slz/ml0VsyU1q4VA=
  expiration: 3600000
  refresh-expiration: 604800000


logging:
  level:
    root: INFO
    org:
      springdoc: DEBUG
      hibernate:
        sql: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
    com.example.services: DEBUG